name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"

    steps:
      # Check-out code to allow workflow to access our repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # with: fetch-depth:0 means we are getting the last commit
          fetch-depth: 0
      # --frozen-lock-file to avoid dependencies changing in CI
      # https://github.com/yarnpkg/yarn/issues/4147
      - name: Install JS Dependencies
        run: yarn install --frozen-lock-file
      # Run ESLINT, Format checks and unit tests
      - name: Run checks
        run: yarn verify

      - name: Build
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v2
      # Uploading an artifact allows for sharing data between jobs and store data once the workflow is finished.
      # https://adamtheautomator.com/github-actions-artifacts-2/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "docs/storybook-static"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
