name: Deployment Pipeline

on:
  push:
    branches: [ci-setup, main] 
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
    # Avoid redundant builds to prevent running more than 1 build in parallel
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-20.04
    steps:
    # Check-out code with GitHub Actions to allow workflow to access our repo
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
        # with: fetch-depth:0 means we are getting the last commit
          fetch-depth: 0
        
      - name: Install JS Dependencies
        run: yarn install

      - name: Run Eslint
        run: yarn run lint

      - name: Run Eslint with '--fix' option
        run: yarn run lint:fix

      - name: Format code
        run: yarn run format
      
  build:
    runs-on: ubuntu-20.04
    steps:
    # Check-out code with GitHub Actions to allow workflow to access our repo
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
        # with: fetch-depth:0 means we are getting the last commit
          fetch-depth: 0
        
      - name: Install JS Dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      # Upload the build so that we can run the test job without having to build again
      - uses: actions/upload-artifact@v2
        with:
          name: components
          path: components

  tests:
  # needs is an array to which we pass the jobs that need to be carried on before this job can be run. Tests need lint and build 
  # to be able to run correctly, otherwise test would run in parallel with build and crash.
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
    # Check-out code with GitHub Actions to allow workflow to access our repo
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
        # with: fetch-depth:0 means we are getting the last commit
          fetch-depth: 0
        
      - name: Install JS Dependencies
        run: yarn install

      # Download the build from the previous job
      - uses: actions/download-artifact@v2
        with:
          name: components
          path: components

      - name: Run Tests
        run: yarn vitest


