name: Test

on:
  pull_request:
    branches: ["4681-changelog-setup"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn ci
      - run: yarn run build
      - run: rm -rf node_modules
      - uses: ./
